services:
  city-services-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # API port
      - "5173:5173"  # UI port
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=3001
    volumes:
      - ./data:/app/api/prisma  # Persist database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s